src/Entity/Crud.php
<?php

namespace App\Entity;

use App\Repository\CrudRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CrudRepository::class)]
class Crud
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 64)]
    private ?string $entity_name = null;

    #[ORM\Column(length: 64)]
    private ?string $form_name = null;

    #[ORM\Column(length: 64)]
    private ?string $route_name = null;

    #[ORM\OneToMany(mappedBy: 'crud', targetEntity: CrudDetail::class)]
    private Collection $crudDetails;

    public function __construct()
    {
        $this->crudDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEntityName(): ?string
    {
        return $this->entity_name;
    }

    public function setEntityName(string $entity_name): static
    {
        $this->entity_name = $entity_name;

        return $this;
    }

    public function getFormName(): ?string
    {
        return $this->form_name;
    }

    public function setFormName(string $form_name): static
    {
        $this->form_name = $form_name;

        return $this;
    }

    public function getRouteName(): ?string
    {
        return $this->route_name;
    }

    public function setRouteName(string $route_name): static
    {
        $this->route_name = $route_name;

        return $this;
    }

    /**
     * @return Collection<int, CrudDetail>
     */
    public function getCrudDetails(): Collection
    {
        return $this->crudDetails;
    }

    public function addCrudDetail(CrudDetail $crudDetail): static
    {
        if (!$this->crudDetails->contains($crudDetail)) {
            $this->crudDetails->add($crudDetail);
            $crudDetail->setCrud($this);
        }

        return $this;
    }

    public function removeCrudDetail(CrudDetail $crudDetail): static
    {
        if ($this->crudDetails->removeElement($crudDetail)) {
            // set the owning side to null (unless already changed)
            if ($crudDetail->getCrud() === $this) {
                $crudDetail->setCrud(null);
            }
        }

        return $this;
    }
}

src/Entity/CrudDetail.php
<?php

namespace App\Entity;

use App\Repository\CrudDetailRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CrudDetailRepository::class)]
class CrudDetail
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 64)]
    private ?string $name = null;

    #[ORM\Column(length: 4)]
    private ?string $type = null;

    #[ORM\Column(nullable: true)]
    private ?array $setting = null;

    #[ORM\ManyToOne(inversedBy: 'crudDetails')]
    private ?Crud $crud = null;

    #[ORM\Column]
    private ?int $datatable = null;

    #[ORM\Column(length: 255)]
    private ?string $label = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getSetting(): ?array
    {
        return $this->setting;
    }

    public function setSetting(?array $setting): static
    {
        $this->setting = $setting;

        return $this;
    }

    public function getCrud(): ?Crud
    {
        return $this->crud;
    }

    public function setCrud(?Crud $crud): static
    {
        $this->crud = $crud;

        return $this;
    }

    public function getDatatable(): ?int
    {
        return $this->datatable;
    }

    public function setDatatable(int $datatable): static
    {
        $this->datatable = $datatable;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): static
    {
        $this->label = $label;

        return $this;
    }
}

src/Controller/CrudDetailController.php
<?php

namespace App\Controller;

use App\Entity\Crud;
use App\Entity\CrudDetail;
use App\Repository\CrudDetailRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CrudDetailController extends AbstractController
{
    #[Route('/crud/detail/{id}', name: 'app_crud_detail')]
    public function index(int $id, EntityManagerInterface $entitiyManager): Response
    {
        $crud = $entitiyManager->getRepository(Crud::class)->find($id);
        if (!$crud) {
            throw $this->createNotFoundException(
                'Id Not Found For Id: '.$id
            );
        }
        return $this->render('crud_detail/index.html.twig', [
            'crud' => $crud,
        ]);
    }

    #[Route('/crud/detail/{id}/fields', name:'app_crud_detail_fields', methods:['GET'])]
    public function fields(int $id, CrudDetailRepository $crudDetail)
    {
        $crud = $crudDetail->findBy(['crud' => $id]);
        $data = [];
        foreach ($crud as $key => $value) {
            $array = [
                'id' => $value->getId(),
                'name' => $value->getName(),
                'crudName' => $value->getCrud()->getEntityName(),
                'type' => $value->getType(),
                'setting' => $value->getSetting()
            ];
            array_push($data, $array);
        }
        return $this->json($data);
    }

    #[Route('/crud/detail/{id}/edit', name: 'app_crud_detail_edit', methods: ['GET'])]
    public function edit(CrudDetail $crudDetail, int $id) 
    {
        $data = [
            'id' => $crudDetail->getId(),
            'name' => $crudDetail->getName(),
            'crudName' => $crudDetail->getCrud()->getEntityName(),
            'type' => $crudDetail->getType(),
            'setting' => $crudDetail->getSetting(),
            'datatable' => $crudDetail->getDatatable(),
            'label' => $crudDetail->getLabel()
        ];
        return $this->json($data);
    }

    #[Route('/crud/detail/{id}/save', name:'app_crud_detail_save', methods:['POST'])]
    public function save(Request $request, EntityManagerInterface $em, int $id)
    {
        $data = $request->request->all();

        $crud = $em->getRepository(Crud::class)->find($id);
        if ($data['saveMethod'] == 'save') {
            $crudDetail = new CrudDetail();
        } else {
            $crudDetail = new CrudDetail();
            $crudDetail = $em->getRepository(CrudDetail::class)->find($data['id']);
        }
        $crudDetail->setName($data['nameField']);
        $crudDetail->setType($data['typeField']);
        $crudDetail->setCrud($crud);
        $crudDetail->setDatatable($data['datatableField']);
        $crudDetail->setLabel($data['labelField']);
        if ($data['saveMethod'] == 'save') {
            $em->persist($crudDetail);
        }
        $em->flush();
        return $this->json([
            'info' => 'success',
            'message' => 'Save Data Success'
        ]);
    }

    #[Route(path: '/crud/detail/{id}/entity', name: 'app_crud_detail_entity', methods: ['GET'])]
    public function entity(int $id, EntityManagerInterface $entitiyManager) : Response
    {
        $con = $entitiyManager->getConnection();
        $sm = $con->getSchemaManager();
        // $columns = $sm->listTableColumns('siswa');
        // $columnNames = [];
        // foreach($columns as $column){
        //     $columnNames[] = $column->getName();
        // }

        $table = $sm->listTableDetails('siswa');
        return $this->json($table);
    }
}

templates/crud_detail/index.html.twig
{% extends 'adminlte.html.twig' %}

{% block title %}CRUD{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/dataTables.bootstrap.css" integrity="sha512-GgMRV6UXqOFCfW5B+j4bvTRCU9vGYA9o46NiaMUrlHGcSJHg68o7X7IGAPl+pvaApCjCU3C5MsWhgDGGkmaaPg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/dataTables.bootstrap4.css" integrity="sha512-dufHiZudcIxbGBWe8xgxnZZyrDstYWv60bXzUww0cl9az56Y86/qEzGDW3lYkQxCFmr/H79i2Kl+uip/KEmw7Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block body %}
<div class="content-wrapper">

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Crud Field</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item">Crud</li>
                        <li class="breadcrumb-item active">Field</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Your Field</h3>
                <div class="card-tools">
                    <a href="{{ path('app_crud_index')}}" class="btn btn-tool">
                        <i class="fas fa-list"></i>
                    </a>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <td>{{ crud.id }}</td>
                        </tr>
                        <tr>
                            <th>Entity_name</th>
                            <td>{{ crud.entityName }}</td>
                        </tr>
                        <tr>
                            <th>Form_name</th>
                            <td>{{ crud.formName }}</td>
                        </tr>
                        <tr>
                            <th>Route_name</th>
                            <td>{{ crud.routeName }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <button class="btn btn-primary btn-block mb-1" onclick="tambahField()">Tambah Field</button>
                <div class="card card-outline card-primary">
                    <div class="card-body">
                        <div id="field">
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-10">
                <button type="button" class="btn btn-primary" onclick="generate()" id="btnGenerate"><i class="fa fa-edit"></i> Generate</button>
                <div class="card card-outline card-primary mt-1" id="cardSetting">
                    <div class="card-body">
                        <form action="" id="formSetting">
                            <input type="hidden" name="id" value="">
                            <input type="hidden" name="saveMethod" value="">
                            <div id="divField"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </section>

</div>

{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js" integrity="sha512-BkpSL20WETFylMrcirBahHfSnY++H2O1W+UnEEO4yNIl+jI2+zowyoGJpbtk6bx97fBXf++WJHSSK2MV4ghPcg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/dataTables.bootstrap4.min.js" integrity="sha512-OQlawZneA7zzfI6B1n1tjUuo3C5mtYuAWpQdg+iI9mkDoo7iFzTqnQHf+K5ThOWNJ9AbXL4+ZDwH7ykySPQc+A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $(document).ready(function () {
            getField();
        });

        function getField() {
            $.ajax({
                type: "GET",
                url: "{{ path('app_crud_detail_fields', {'id': crud.id}) }}",
                dataType: "JSON",
                success: function (response) {
                    if(response.length >= 1) {
                        var html = `<ul class="nav nav-pills flex-column">`;
                        $.each(response, function (indexInArray, valueOfElement) { 
                            html += `<li class="nav-item active">
                                    <a href="javascript:;" onclick="editField(`+valueOfElement.id+`)" class="nav-link">
                                        `+valueOfElement.name+`
                                    </a>
                                </li>`;
                        });
                        html += `</ul>`;
                        $('#field').html(html);
                    } else {
                        $('#field').html(`<div class="text-center">data field is empty</div>`);
                    }
                }
            });
        }

        function generateForm() {
            var html = `<div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Name Property Entity</label>
                                <input type="text" class="form-control" name="nameField" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Label</label>
                                <input type="text" class="form-control" name="labelField" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Type</label>
                                <select name="typeField" class="form-control" required>
                                    <option value="">-</option>
                                    <option value="1">String</option>
                                    <option value="2">Textarea</option>
                                    <option value="3">Image</option>
                                    <option value="4">Rupiah</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label class="label">view table</label>
                            <select class="form-control" name="datatableField">
                                <option value=""></option>
                                <option value="1">Ya</option>
                                <option value="2">Tidak</option>
                            </select>
                        </div>
                    </div>
                    
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> simpan</button>`;
            return html;
        }

        function tambahField() {
            $('[name="saveMethod"]').val('save');
            var html = generateForm();
            $('#divField').html(html);
        }

        function editField(id) {
            $('[name="saveMethod"]').val('update');
            cardOverlayStart('cardSetting');
            $.ajax({
                type: "get",
                url: "/crud/detail/"+id+"/edit",
                dataType: "json",
                success: function (response) {
                    var html = generateForm();
                    $('#divField').html(html);
                    $('[name="id"]').val(id);
                    $('[name="nameField"]').val(response.name);
                    $('[name="typeField"]').val(response.type);
                    $('[name="datatableField"]').val(response.datatable);
                    $('[name="labelField"]').val(response.label);
                    cardOverlayStop('cardSetting');
                }
            });
        }

        $('#formSetting').submit(function (e) { 
            e.preventDefault();
            $.ajax({
                type: "post",
                url: "{{ path('app_crud_detail_save', {id: crud.id}) }}",
                data: $('#formSetting').serialize(),
                dataType: "JSON",
                success: function (response) {
                    Swal.fire({
                        title: "Notification !",
                        text: response.message,
                        icon: response.info
                    }).then(function(e) {
                        getField();
                        $('#formSetting')[0].reset();
                    });
                },
                error: function (jqXHR) {
                    console.log(jqXHR.responseText);
                }
            });
        });

        function generate() {
            btnLoadingStart('btnGenerate');
            $.ajax({
                type: "GET",
                url: "{{ path('app_crud_generate', {id : crud.id}) }}",
                dataType: "json",
                success: function (response) {
                    Swal.fire({
                        title: "Notification !",
                        text: response.message,
                        icon: response.info
                    }).then(function (e) {
                        btnLoadingStop('btnGenerate');
                    });;
                }
            });
        }
    </script>
{% endblock %}